// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/json/": {
            "get": {
                "description": "\u003cp\u003eReturns the cached normalized schema document that backs all validation endpoints.\u003c/p\u003e",
                "produces": [
                    "application/schema+json"
                ],
                "tags": [
                    "Schema"
                ],
                "summary": "Retrieve the normalized APISIX JSON Schema",
                "responses": {
                    "200": {
                        "description": "Normalized JSON Schema document",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sources": {
            "get": {
                "description": "\u003cp\u003eReturns the list of discovered fragment paths.\u003c/p\u003e\n\u003cp\u003eEvery response includes ` + "`" + `ETag` + "`" + `, ` + "`" + `Last-Modified` + "`" + `, and ` + "`" + `Cache-Control: public, max-age=0, must-revalidate` + "`" + `, so clients should reuse those values and revalidate with ` + "`" + `If-None-Match` + "`" + ` or ` + "`" + `If-Modified-Since` + "`" + ` to bump into ` + "`" + `304 Not Modified` + "`" + ` when nothing changed.\u003c/p\u003e",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema"
                ],
                "summary": "List known source fragments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Previously returned ETag used to skip unnecessary downloads",
                        "name": "If-None-Match",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "RFC1123 timestamp to compare against the ` + "`" + `Last-Modified` + "`" + ` header",
                        "name": "If-Modified-Since",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available source paths",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "No sources found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sources/{path}": {
            "get": {
                "description": "\u003cp\u003eReturns the raw YAML payload for a given path.\u003c/p\u003e\n\u003cp\u003eEvery response includes ` + "`" + `ETag` + "`" + `, ` + "`" + `Last-Modified` + "`" + `, and ` + "`" + `Cache-Control: public, max-age=0, must-revalidate` + "`" + `, so clients should reuse those values and revalidate with ` + "`" + `If-None-Match` + "`" + ` or ` + "`" + `If-Modified-Since` + "`" + ` to bump into ` + "`" + `304 Not Modified` + "`" + ` when nothing changed.\u003c/p\u003e",
                "produces": [
                    "application/yaml"
                ],
                "tags": [
                    "Schema"
                ],
                "summary": "Fetch a single fragment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relative fragment path (e.g., ` + "`" + `routes/example.yaml` + "`" + `); omit to list paths.",
                        "name": "path",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Previously returned ETag used to skip unnecessary downloads",
                        "name": "If-None-Match",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "RFC1123 timestamp to compare against the ` + "`" + `Last-Modified` + "`" + ` header",
                        "name": "If-Modified-Since",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "YAML fragment content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Fragment not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/validate": {
            "post": {
                "description": "\u003cp\u003ePosts JSON or YAML content along with optional query params used as environment overrides.\u003c/p\u003e\n\u003cp\u003eAny number of query keys/values is allowed; they are applied to the snippet before validation, so clients can push substitutions such as ` + "`" + `?DOMAIN=apisix.org` + "`" + ` or ` + "`" + `?consumer=bob` + "`" + `.\u003c/p\u003e\n\u003cp\u003eExample URLs: ` + "`" + `/schema/validate/routes/example.yaml?DOMAIN=apisix.org\u0026consumer=bob` + "`" + `.\u003c/p\u003e\n\u003cp\u003eEvery response includes ` + "`" + `ETag` + "`" + `, ` + "`" + `Last-Modified` + "`" + `, and ` + "`" + `Cache-Control: public, max-age=0, must-revalidate` + "`" + `, so clients should reuse those values and revalidate with ` + "`" + `If-None-Match` + "`" + ` or ` + "`" + `If-Modified-Since` + "`" + ` to bump into ` + "`" + `304 Not Modified` + "`" + ` when nothing changed.\u003c/p\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema"
                ],
                "summary": "Validate an inline payload against the schema",
                "parameters": [
                    {
                        "description": "JSON or YAML payload to validate",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Validation result",
                        "schema": {
                            "$ref": "#/definitions/schema.ValidationResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed or empty payload",
                        "schema": {
                            "$ref": "#/definitions/schema.ValidationResponse"
                        }
                    }
                }
            }
        },
        "/validate/{path}": {
            "get": {
                "description": "\u003cp\u003eValidates the fragment referenced by the request path while treating every query parameter as an environment override.\u003c/p\u003e\n\u003cp\u003eAny number of query keys/values is allowed; they are applied to the snippet before validation, so clients can push substitutions such as ` + "`" + `?DOMAIN=apisix.org` + "`" + ` or ` + "`" + `?consumer=bob` + "`" + `.\u003c/p\u003e\n\u003cp\u003eExample URLs: ` + "`" + `/schema/validate/routes/example.yaml?DOMAIN=apisix.org\u0026consumer=bob` + "`" + `.\u003c/p\u003e\n\u003cp\u003eEvery response includes ` + "`" + `ETag` + "`" + `, ` + "`" + `Last-Modified` + "`" + `, and ` + "`" + `Cache-Control: public, max-age=0, must-revalidate` + "`" + `, so clients should reuse those values and revalidate with ` + "`" + `If-None-Match` + "`" + ` or ` + "`" + `If-Modified-Since` + "`" + ` to bump into ` + "`" + `304 Not Modified` + "`" + ` when nothing changed.\u003c/p\u003e",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema"
                ],
                "summary": "Validate a cached source fragment with environment overrides",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relative fragment path to validate",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ETag from a prior validation response",
                        "name": "If-None-Match",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Timestamp to compare against the validation's Last-Modified",
                        "name": "If-Modified-Since",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Validation result",
                        "schema": {
                            "$ref": "#/definitions/schema.ValidationResponse"
                        }
                    },
                    "404": {
                        "description": "Fragment not found",
                        "schema": {
                            "$ref": "#/definitions/schema.ValidationResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schema.ValidationIssue": {
            "type": "object",
            "properties": {
                "absoluteKeywordLocation": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "instanceLocation": {
                    "type": "string"
                },
                "keywordLocation": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "schemaLocation": {
                    "type": "string"
                }
            }
        },
        "schema.ValidationResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.ValidationIssue"
                    }
                },
                "valid": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/schema",
	Schemes:          []string{},
	Title:            "Sixpack Schema Control API",
	Description:      "Control plane helpers for introspecting the APISIX schema and validating source fragments. The API exposes a few cached read endpoints; clients should revalidate changes by reusing the ETag/Last-Modified headers that the server always emits and honoring `Cache-Control: public, max-age=0, must-revalidate`.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
