{{- $root := . -}}
{{- $fullname := include "smc-apisix-rules.fullname" $root -}}
{{- range $name, $cfg := .Values.configmaps }}
{{- with $cfg.ingress }}
{{- if .enabled }}
{{- $svcName := $root.Values.commonService.name -}}
{{- $svcPort := $root.Values.commonService.port -}}
{{- with $cfg.service }}
{{- $svcName = default (printf "%s-%s" $fullname $name) .name -}}
{{- $svcPort = .port -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" $fullname $name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "smc-apisix-rules.labels" $root | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- range $name, $cfg := .Values.secrets }}
{{- with $cfg.ingress }}
{{- if .enabled }}
{{- $svcName := $root.Values.commonService.name -}}
{{- $svcPort := $root.Values.commonService.port -}}
{{- with $cfg.service }}
{{- $svcName = default (printf "%s-%s" $fullname $name) .name -}}
{{- $svcPort = .port -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" $fullname $name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "smc-apisix-rules.labels" $root | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
