{{- $root := . -}}
{{- $fullname := include "smc-apisix-rules.fullname" $root -}}
{{- range $name, $cfg := .Values.secrets }}
{{- if $cfg.snippet }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $fullname $name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "smc-apisix-rules.labels" $root | nindent 4 }}
    cuesisx.apisix/snippet: "true"
type: Opaque
stringData:
  snippet.yaml: |-
{{ $cfg.snippet | nindent 4 }}
---
{{- end }}
{{- end }}
