{{- $root := . -}}
{{- $fullname := include "smc-apisix-rules.fullname" $root -}}
{{- range $name, $cfg := .Values.configmaps }}
{{- with $cfg.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-%s" $fullname $name) .name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "smc-apisix-rules.labels" $root | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ $root.Values.commonService.targetPort }}
      protocol: TCP
  selector:
    {{- toYaml $root.Values.commonService.selector | nindent 4 }}
---
{{- end }}
{{- end }}
{{- range $name, $cfg := .Values.secrets }}
{{- with $cfg.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-%s" $fullname $name) .name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "smc-apisix-rules.labels" $root | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ $root.Values.commonService.targetPort }}
      protocol: TCP
  selector:
    {{- toYaml $root.Values.commonService.selector | nindent 4 }}
---
{{- end }}
{{- end }}
